version: '3.4'

services:
  acc-text-api:
    image: acctext/api:latest
    networks:
      - default
    ports: ["3001:3001"]
    environment:
      GF_ENDPOINT: "http://gf:8000"
      DISPLAY_ERROR: "TRUE"
      ENABLE_ENRICH: "FALSE"
      ENABLE_REF_EXPR: "FALSE"
      DB_IMPLEMENTATION: "datomic"
      DB_URI: "datomic:free://datomic-transactor:4334/acc-text?password=datomic"
      DATA_FILES: "/opt/data-files"
      DICT_PATH: "/opt/dictionary"
      DOCUMENT_PLANS: "/opt/document-plans"
      ENABLED_LANGUAGES: "Eng"
    volumes:
      - ./api/resources:/opt
    depends_on:
      - datomic-transactor
      - gf

  datomic-transactor:
    image: "gordonstratton/datomic-free-transactor:latest"
    environment:
      DATOMIC_HOST: "datomic-transactor"
      DATOMIC_ALT_HOST: "acc-text-api"
    volumes:
      - datomic:/srv/datomic/data
      - ./accelerated-text/transactor-logback.xml:/srv/datomic/bin/logback.xml

  gf:
    image: acctext/gf:latest
    ports: ["8001:8000"]

  acc-text-front-end:
    image: acctext/frontend:latest
    ports: ["8080:80"]
  
  reaction-api:
    image: reactioncommerce/reaction:3.3.0
    depends_on:
      - reaction-mongo
    environment:
      - MONGO_URL=mongodb://reaction-mongo:27017/reaction
      - ROOT_URL=http://localhost:3000
      - STRIPE_API_KEY=YOUR_PRIVATE_STRIPE_API_KEY
    ports:
      - "3000:3000"
    volumes:
      - ./reaction-admin/imports/plugins/custom/reaction-acc-text-import/translations:/usr/local/src/app/src/plugins/custom/acc-text-import
      - ./registerPlugins.override.js:/usr/local/src/app/src/registerPlugins.js

  reaction-mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-db:/data/db


  reaction-admin:
    # The main `docker-compose.yml` has an `image` prop. Unfortunately, when we
    # add `build` prop here, it changes the meaning of that `image` prop to
    # "tag the built image with this image name". This has the effect of breaking
    # the app after you've run with the override and then go back to running without
    # it, because now `reactioncommerce/admin:trunk` would actually be your dev image.
    # To work around this issue, we specify a different tag name here, which does not
    # match any of our published tags.
    image: reactioncommerce/admin:local-dev
    build:
      context: ./reaction-admin/
      dockerfile: Dockerfile-dev
    command: bash -c "export PATH=$PATH:/home/node/.meteor && npm install --no-audit && node ./.reaction/waitForMongo.js && node --experimental-modules ./.reaction/scripts/run.mjs"
    environment:
      - MONGO_URL=mongodb://reaction-mongo:27017/reaction
      - PORT=4080
      - METEOR_DISABLE_OPTIMISTIC_CACHING=1
      - METEOR_WATCH_POLLING_INTERVAL_MS=10000
      - MONGO_OPLOG_URL=mongodb://reaction-mongo:27017/local
      - OAUTH2_ADMIN_URL=http://hydra:4445
      - OAUTH2_IDP_PUBLIC_CHANGE_PASSWORD_URL=http://localhost:4100/account/change-password?email=EMAIL&from=FROM
      - OAUTH2_PUBLIC_URL=http://localhost:4444
      - PUBLIC_GRAPHQL_API_URL_HTTP=http://localhost:3000/graphql
      - PUBLIC_GRAPHQL_API_URL_WS=ws://localhost:3000/graphql
      - PUBLIC_FILES_BASE_URL=http://localhost:3000
      - PUBLIC_I18N_BASE_URL=http://localhost:3000
      - PUBLIC_STOREFRONT_HOME_URL=http://localhost:4000
      - ROOT_URL=http://localhost:4080
      - UPLOAD_URL=http://reaction-api:3000/assets/uploads
    ports:
      - "4080:4080"
    volumes:
      - ./reaction-admin/:/usr/local/src/app:cached
      - reaction_meteor_local:/usr/local/src/app/.meteor/local
      - reaction_node_modules:/usr/local/src/app/node_modules # do not link node_modules in, and persist it between dc up runs

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=hydra
    ports:
      - 5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  hydra-migrate:
    image: oryd/hydra:v1.0.8
    command: migrate sql -e -y
    depends_on:
      - postgres
    environment:
      - DSN=postgres://hydra:changeme@postgres:5432/hydra?sslmode=disable
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=true
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=http://localhost:4080
      - SERVE_PUBLIC_CORS_ENABLED=true
      - URLS_CONSENT=http://localhost:4100/consent
      - URLS_ERROR=http://localhost:4100/account/oauth-error
      - URLS_LOGIN=http://localhost:4100/login
      - URLS_LOGOUT=http://localhost:4100/logout
      - URLS_SELF_ISSUER=http://localhost:4444
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.0.8
    command: serve all --dangerous-force-http
    depends_on:
      - hydra-migrate
      - postgres
    ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    environment:
      - DSN=postgres://hydra:changeme@postgres:5432/hydra?sslmode=disable
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=true
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=http://localhost:4080
      - SERVE_PUBLIC_CORS_ENABLED=true
      - URLS_CONSENT=http://localhost:4100/consent
      - URLS_ERROR=http://localhost:4100/account/oauth-error
      - URLS_LOGIN=http://localhost:4100/login
      - URLS_LOGOUT=http://localhost:4100/logout
      - URLS_SELF_ISSUER=http://localhost:4444
    restart: unless-stopped

  web:
    image: reactioncommerce/example-storefront:3.0.0
    depends_on:
      - hydra
      - identity
    environment:
      - CANONICAL_URL=http://localhost:4000
      - ENABLE_SPA_ROUTING=true
      - EXTERNAL_GRAPHQL_URL=http://localhost:3000/graphql
      - INTERNAL_GRAPHQL_URL=http://reaction-api:3000/graphql
      - OAUTH2_ADMIN_PORT=4445
      - OAUTH2_ADMIN_URL=http://hydra:4445
      - OAUTH2_AUTH_URL=http://localhost:4444/oauth2/auth
      - OAUTH2_CLIENT_ID=example-storefront
      - OAUTH2_CLIENT_SECRET=CHANGEME
      - OAUTH2_PUBLIC_LOGOUT_URL=http://localhost:4444/oauth2/sessions/logout
      - OAUTH2_HOST=hydra.reaction.localhost
      - OAUTH2_IDP_PUBLIC_CHANGE_PASSWORD_URL=http://localhost:4100/account/change-password?email=EMAIL&from=FROM
      - OAUTH2_IDP_HOST_URL=http://localhost:4100
      - OAUTH2_TOKEN_URL=http://localhost:4444/oauth2/token
      - PORT=4000
      - SEGMENT_ANALYTICS_SKIP_MINIMIZE=true
      - SEGMENT_ANALYTICS_WRITE_KEY=ENTER_KEY_HERE
      - SESSION_MAX_AGE_MS=2592000000
      - SESSION_SECRET=CHANGEME
      - STRIPE_PUBLIC_API_KEY=ENTER_STRIPE_PUBLIC_KEY_HERE
    ports:
      - 4000:4000

  identity:
    image: reactioncommerce/identity:3.0.0
    depends_on:
      - hydra
      - reaction-mongo
      - reaction-api
    environment:
      - API_URL=http://localhost:3000/graphql
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_TOKEN_URL=http://hydra:4444/oauth2/token
      - LOG_LEVEL=debug
      - METEOR_DISABLE_OPTIMISTIC_CACHING=1
      - METEOR_WATCH_POLLING_INTERVAL_MS=10000
      - MONGO_OPLOG_URL=mongodb://reaction-mongo:27017/local
      - MONGO_URL=mongodb://reaction-mongo:27017/reaction
      - OAUTH2_CLIENT_DOMAINS=http://localhost:4000
      - PORT=4100
      - ROOT_URL=http://localhost:4100
    ports:
      - "4100:4100"

volumes:
  mongo-db:
  reaction_meteor_local:
  reaction_node_modules:
  postgres-data:
  datomic:
    name: acc-text_datomic
