version: '3.4'

services:
  document-plans-setup:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'sh prepare-data.sh'
    environment:
      ACC_TEXT_URL: http://acc-text-api:3001
    restart: on-failure
